### PR TITLE
A few miscellaneous things

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Deleted redundant files (.idea, unused proguard, etc.)

### 2nd commit
- Updated Gradle wrapper to 6.0.1

### 3rd commit
- Updated Android Studio to 3.5.3
- Updated Gson to 2.8.6
- Added Java 8 compatibility
- Disabled an annoying lint
- Shrink APK by tens of kilobytes by not packaging META-INF (so much storage saved!)

### 4th commit
- Added an .editorconfig for code consistency
- Automatically reformatted code to .editorconfig

### 5th commit
- Simplified some if statements
- Merge duplicate cases
- Convert anonymous Java expressions to lambdas
- Update copyright in strings

### 6th commit
- Correct some things in the README
- Add license text at the end

### CODE REVIEW

**Comment by flackbash** [comment]
Thank you! I'll try to have a look at it next week

**Comment by flackbash** [comment]
Great, thanks for the massive clean-up! I just had a closer look at it. 

The only change I would request is to remove the first commit (5eac56c).
At the very least the .idea/modules.xml file should not be deleted and not be added to gitignore.
I think the proguard-rules file should also be kept for future use.
Did you have strong reasons for removing the other .idea files and adding the entire .idea folder to gitignore?

**Comment by TacoTheDank** [comment]
@flackbash What I often see in other projects is the .idea files causing a lot of unnecessary noise in commits, as they often have changes made to them automatically, and most of the time they aren't needed in GitHub, as they're generated files.

You can add back the proguard and other files if you wish by making the commit on my repo (I allow edits by maintainers), or on yours after merging. (I don't quite have the time right now to do this.)

**Comment by flackbash** [comment]
Ok, I'll leave the files in there for now and reconsider this if any problems come up in future. 

Are you fine with me doing a git rebase + force push in your repo? If possible, I would prefer to keep the git history clean and not make an additional commit to undo the previous one.

**Comment by TacoTheDank** [comment]
@flackbash Sorry I'm late, yeah you can do that

**Comment by flackbash** [comment]
Perfect. Thanks again!

**Pull request merged**
