### PR TITLE
Replace outdated SpeedDial FAB library (closes #156)

### LINKED ISSUE #156: Drop legacy com.getbase:floatingactionbutton
Version 1.10.1 is from 2015. It is only library which uses old android.support libraries, which requires Jetifier to be enabled.
Floating Action Button can be implemented usual way with Material library:

* [FloatingActionButton | Android Developers](https://developer.android.com/reference/com/google/android/material/floatingactionbutton/FloatingActionButton)
* [Add a Floating Action Button | Android Developers](https://developer.android.com/guide/topics/ui/floating-action-button)

### PR DESCRIPTION
**Pull request by TacoTheDank**
Closes #156.

I used this library: https://github.com/nambicompany/expandable-fab

I have attached an APK (with a different package name) so that you can see the change for yourself and compare them side-by-side.

[app-release.zip](https://github.com/flackbash/AudioAnchor/files/8642656/app-release.zip)

(I also removed the unused tests and reorganized the libraries.)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@flackbash Have you gotten a chance to look at this yet?

**Comment by flackbash** [comment]
On it :)

**Comment by TacoTheDank** [comment]
> The other thing is that I find the fade in of the buttons a bit annoying because it takes so long. It's a small detail, but are you aware of any option to speed this up? If not I'll still merge it.

@flackbash Funnily enough, that was one of my concerns too when replacing the library for this project, so I had opened an issue [here](https://github.com/nambicompany/expandable-fab/issues/43). It seems as though it's a side effect of the library's design.

**Comment by flackbash** [comment]
I just had a look at FloatingActionButtonSpeedDial and I must say at first sight I find it a lot more convincing, especially due to the active development (latest commit was three days ago) and the 10x higher number of stars.
What do you mean by usage design?

**Comment by TacoTheDank** [comment]
> especially due to the active development

That's fairly recent; if you go back into the commit history, it was previously at May 2021.

> What do you mean by usage design?

I'm not good at words. I meant like how it needs to be set up in order for it to work. Don't worry about it lol.

So I'm assuming you prefer FloatingActionButtonSpeedDial, then. I'll work on using that one.

**Comment by flackbash** [comment]
> That's fairly recent; if you go back into the commit history, it was previously at May 2021.
Ah you're right. I do still have a better feeling about FloatingActionButtonSpeedDial though, yes.

**Comment by TacoTheDank** [comment]
@flackbash I keep getting this stupid bug with the FloatingActionButtonSpeedDial where the mini FAB icons are invisible no matter what I do. Also, the text doesn't wrap (just ends in ellipses), so I had to shorten both of them to "Add subdirectory" and "Add parent directory".

Alternatively, it might just be better to create a custom dialog that uses the current listview already shown, but also adds a checkbox above the dialog buttons that's labeled something like "include subdirectories of chosen folder." You could check or uncheck this, and the result would be parsed accordingly when "select directory" is pressed. This would allow us to get rid of this library entirely (and would likely make more sense in terms of UI).

**Comment by flackbash** [comment]
Ok, thank you for your effort!

I do like the floating action button menu more than the checkbox idea. With the current solution I think the options are properly explained and the difference of the options becomes clearer. Also, the meaning of the icons that are then displayed in the list view of the activity for each added directory is introduced and explained with the floating action button solution.

In that case, I'm still considering just merging the current code with the library I'm not fully convinced by, but my tendency is more towards just leaving it as is right now.

**Comment by TacoTheDank** [comment]
> In that case, I'm still considering just merging the current code with the library I'm not fully convinced by, but my tendency is more towards just leaving it as is right now.

That's ok.👍

I'll just bring up the context once more for this change: #156

Jetifier slows down build performance, and the outdated FAB library is the only one still using old support libraries that require Jetifier. That would be my argument for at least merging it as is.

From my testing, the only drawback of expandable-fab is the longer fade-in. Everything else is supported out-of-the-box with no hacks needed to make it work. Also, it was quite easy to migrate and set up.

But with FloatingActionButtonSpeedDial, the drawbacks are that the label text doesn't wrap, and the FAB icons are glitchy for some reason (so not even usable for us). Also, from my experience, its API is much more cumbersome.

Ultimately it's up to you though.

**Comment by flackbash** [comment]
Convinced. Thanks again for your work!

**Comment by TacoTheDank** [comment]
Yw!

Also, I forgot to remove `android.enableJetifier=true` (the most important part). Could you take care of that?

**Comment by flackbash** [comment]
Of course.

**Pull request merged**
