### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by PtilopsisLeucotis**
Added Russian translation

### CODE REVIEW

**Comment by flackbash** [comment]
Awesome, thanks :)

Just one request: Can you please change the copyright year to *2018-2020* as you did in your other PR?
You can add another commit that fixes this and then use `git rebase -i HEAD~2` to squash the two commits into one, followed by `git push --force`. [This](https://www.internalpointers.com/post/squash-commits-into-one-git) might help if you run into problems.

**Comment by PtilopsisLeucotis** [comment]
No problems, I will try to do it tomorrow. I expected, that other PR will be merged before this one :)

**Comment by PtilopsisLeucotis** [comment]
No problems, I will try to do it tomorrow. I expected, that this PR will be merged before other one :)

**Comment by PtilopsisLeucotis** [comment]
I changed copyright year.

**Comment by flackbash** [comment]
Nice :) now you can just squash these two commits using the commands from my previous comment. Let me know if you have any problems.

**Comment by PtilopsisLeucotis** [comment]
Thanks for help.

I did squash commits and push this squashed commit. I hope it was done right :)

**Comment by flackbash** [comment]
Perfect, thanks :)

**Pull request merged**
