### PR TITLE
Mark some strings as not translatable

### PR DESCRIPTION
**Pull request by PtilopsisLeucotis**
I mark some strings as not translatable in files strings.xml
Need I squash all commits to single one or not?

### CODE REVIEW

**Comment by flackbash** [comment]
Exactly, you should squash them all into a single commit because they are all addressing a single issue (marking strings as not translatable) and each sub-problem (i.e. marking a single string as not translatable) only required very minor changes.

But first, could you add another commit that removes the non-translatable strings from the strings.xml for all locales except the default one? I did not pay attention to that before, but actually non-translatable strings should not appear in the other locales at all.
It would be great if you could remove all the non-translatable strings from the strings.xml for the non-default locales (nl, pl and ru). Alternatively you can just remove those which you marked as non-translatable in your commits and I'll do the rest later.

Once you've committed the changes you can squash them all into a single commit.

(If we were to be really exact, there should probably be two commits. One commit *"Mark strings as not translatable"* in which you mark some strings as not translatable in the default locale and remove them from the other locales and another commit *"Remove non-translatable strings from non-default locales"* in which you remove the already existing non-translatable strings from the other locales. But it's fine if you do it all in one commit.)

**Comment by PtilopsisLeucotis** [comment]
No problems,  I'll make two commits, as you describe above, next week.

**Comment by PtilopsisLeucotis** [comment]
I pushed the commits, that you have described above: "Mark strings as not translatable" and "Remove non-translatable strings from non-default locales".
I have another thought: does it make sense to move non-translatable strings to separate file e.g. donttranslatable.xml so that the strings (translatable and not-translatable) are not mixed in one file strings.xml?

**Comment by flackbash** [comment]
Great, looks good!

Yes, you're right, we could do that. See also [here](http://tools.android.com/recent/non-translatablestrings).
On the one hand, there are some strings which kinda belong together, e.g. the label, key and default value of an option in the settings and it makes sense to have them in the same place. Also, when using the Android Studio translation editor it will tell you not to translate non-translatables so in that case having an extra file or not does not matter.
On the other hand, it would make it more straight forward for people without Android Studio to contribute (they would probably copy the `values/strings.xml` file and would then have to manually delete all non-translatables).
I'm on the fence about it at the moment What do you think?

**Comment by PtilopsisLeucotis** [comment]
I think, that having two files (one with translatable strings and other with non-translatable strings) will be a more versatile solution, because it will be at the same time convenient for people using Android Studio, and not using it for translate. 
Having some strings together linked by context can be useful to the programmer rather than the translator, because key and default value are internal entities of the program and are not required to translate the corresponding label.
It probably make sense to keep in file `strings.xml` lines like `<string name="time_completed" translatable="false">%s / %s</string>` which are available into the GUI, but I'm not fully sure of that.

**Comment by flackbash** [comment]
I don't have a strong opinion about it. So if you like you can implement it and just add another commit here or create another pull request.
Just let me know whether you want to do it.
The only thing is that if we are to separate translatables from non-translatables, then I would do it consistently and not keep any non-translatables in strings.xml.

**Comment by PtilopsisLeucotis** [comment]
I have added the commit, that moves all non-translatable strings to separate file `donttranslatable.xml`

**Comment by flackbash** [comment]
Great!
One last thing ;) Now in the `donttranslate.xml` file we really have the problem of line separators that do not match. It seems you are working on a Windows system, so the line separator in this file is set to CRLF while it is set to LF in all other files.
If you are using Android Studio you can simply resolve this by setting the line separator to LF at the bottom of the screen for the `donttranslate.xml` file. See also [this](https://stackoverflow.com/questions/44989520/android-studio-crlf-vs-lf-for-a-git-based-multiplatform-project) question for help.
The last answer describes how you can set the default line separator in Android Studio (though it seems that this does not have any effect on existing files).

**Comment by PtilopsisLeucotis** [comment]
Thank you for your advices and for our help! I actually have Android Studio on laptop with Ubuntu and PC with Windows, when I use Notepad++.  Probably on PC with Windows I was edited that file last time. I was not expect, that may take a place problem with line separator. I'll correct this problem.

**Comment by PtilopsisLeucotis** [comment]
Done.

**Comment by flackbash** [comment]
Great, thanks :)

**Pull request merged**
