### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by PtilopsisLeucotis**

### CODE REVIEW

**Comment by flackbash** [comment]
:) thanks! Could you also adjust the string with the key `no_albums` ? Its value has changed.

**Comment by PtilopsisLeucotis** [comment]
Of course, I'll correct key no_albums too, no problem :)

**Comment by PtilopsisLeucotis** [comment]
Done! :)

**Comment by flackbash** [comment]
Great, thank you!

**Pull request merged**
