### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by jubalh** [comment]
Cool. I just see that when I look at https://github.com/flackbash/AudioAnchor/commits/master so far all commit messages are in present tense.

**Comment by Vistaus** [comment]
What do you mean?

**Comment by jubalh** [comment]
I mean @flackbash wrote every commit message in present tense "Add bookmark screenshots", "Enable bookmark editing", not "Added bookmark screenshots".
I would suggest adhering to that style.

**Comment by Vistaus** [comment]
But as I said: the contribution stays the same either way, so it shouldn't matter.

"People like clean git repos"

I've committed to a lot of git repos and no one has complained when I used a different tense.

**Comment by flackbash** [comment]
Great, thank you! I would prefer having a consistent commit message style. It's not a big thing, but if you could just quickly use the commands that @jubalh suggested to adjust the commit, that would be great :)

**Comment by Vistaus** [comment]
Alrighty then, done :)

**Comment by flackbash** [comment]
Perfect, thanks!

**Pull request merged**
