### PR TITLE
Fixed issue #63.

### PR DESCRIPTION
**Pull request by drone621**
My original pull request had a bug. I closed it, tested it and have reopened. This fixes the broken progress bar in the notification.

### CODE REVIEW

**Comment by flackbash** [comment]
This looks great for the most part, thank you!

For the record: This pull request consists of the following:
1) Use a different app ID when debugging (so the official release can be run in parallel to a debug version of the app)
2) Don't force orientation to portrait mode
3) Add option to follow system theme
4) Add progress in notification for Android >= 10 (API 29)
5) Remove restricted MEDIA_CONTENT_CONTROL permission.

I'm happy with all of this except the unspecified orientation:
I intentionally forced the orientation to be in portrait mode for 2 reasons:
1) I don't have specific landscape layouts (yet) and thus for example when going into landscape mode in the PlayActivity, on many screens you will not be able to see the time stamps below the progress bar (current time and complete duration).
2)  I'm not (yet) taking special care anywhere to avoid unexpected behavior when changing the orientation within the app, e.g. when changing the orientation while adjusting the skip-forward button interval in the settings. I would accept these minor inconveniences if the orientation was fixed by default and the user could enable auto-rotate in the settings.
However, more pressingly, I had the app crash when switching the orientation in the PlayActivity (unfortunately I can't reproduce the exact situation right now) with:
```
2023-04-23 14:41:25.234 18674-18674/com.prangesoftwaresolutions.audioanchor.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.prangesoftwaresolutions.audioanchor.debug, PID: 18674
    java.lang.RuntimeException: Unable to start service com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService@762eb39 with Intent { cmp=com.prangesoftwaresolutions.audioanchor.debug/com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.prangesoftwaresolutions.audioanchor.models.AudioFile.getCoverPath()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3903)
        at android.app.ActivityThread.access$1700(ActivityThread.java:213)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.prangesoftwaresolutions.audioanchor.models.AudioFile.getCoverPath()' on a null object reference
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.getNotificationImage(MediaPlayerService.java:654)
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.updateMetaData(MediaPlayerService.java:600)
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.initMediaSession(MediaPlayerService.java:593)
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.onStartCommand(MediaPlayerService.java:202)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3884)
        at android.app.ActivityThread.access$1700(ActivityThread.java:213) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6923) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870) 
```

I also had playback stop on screen rotation (for this I started playback in portrait orientation, stopped playback, removed the notification, started playback again and then switched orientation).

If you manage to fix these last two problems (and I don't find any other big problems) plus add an option in the settings where the user can enable or disable orientation change, then I would merge this (and it would indeed be great to have this, see also [here](https://github.com/flackbash/AudioAnchor/issues/45#issuecomment-1147290635)). If not, please remove the orientation change part from your pull request.

Another remark: When changing the app ID for the debugging version I find it a lot less confusing when the app name changes too, e.g. to AudioAnchorDebug (e.g. by adding a debug string.xml with the app name [like here](https://github.com/chickendude/Natibo/pull/28/files)). Otherwise you never know which version on your phone is which. Let me know if you disagree.

**Comment by drone621** [comment]
Sorry. I'd never made a pull request before. I assumed that only the commits I made before the pr would be included in it, and didn't expect anyone to see 2-5. I'm very inexperienced, so I'm not sure I can fix the orientation bugs in a timely manner, and may revert those changes if that is acceptable. Everything else I will try to bring up to standard.

**Comment by flackbash** [comment]
Of course, that's fine :) Let me know if you have problems with reverting, then I can also deal with it.

**Comment by flackbash** [comment]
I merged it and made just a few adjustments:
1) I didn't want an extra file for the app name and instead created a `donttranslate.xml` debug version.
2) I adjusted the code for `setActivityTheme` in `Utils` since otherwise a conversion error is thrown upon startup when switching from the old version to the new one because the setting value was still stored as a boolean but retrieved as a string.

Thanks again for the PR :) I just published a new release and it should be picked up by F-Droid within the next week.

**Pull request merged**
