### PR TITLE
Update AndroidX Media, add Dependabot and CI config

### PR DESCRIPTION
**Pull request by PatrykMis**

### CODE REVIEW

**Comment by TacoTheDank** [comment]
I don't believe this project would need dependabot. There are too few libraries used for it to really be necessary.

**Comment by PatrykMis** [comment]
Doesn't matter I think. It's free, though.

**Comment by flackbash** [comment]
I'm also not a fan of the Dependabot idea I must say. But I'll merge the dependency fixes.

**Comment by flackbash** [comment]
I cherry-picked 53f877f84e6c0757d74f520431bd25002a6bd165, d3371dc36909a0109b2e3098646eb144bd8b9851 and 6e19d619e9cb787eb465be371354cf295f107823 into master. Thanks!

**Pull request closed without merging**
